"""add_ride_templates

Revision ID: 86800a33e9a0
Revises: d5c96dbd3b52
Create Date: 2026-01-10 07:39:50.047665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86800a33e9a0'
down_revision: Union[str, Sequence[str], None] = 'd5c96dbd3b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rides', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rides', type_='unique')
    # ### end Alembic commands ###
