"""Add pickup_time column

Revision ID: 4a971acbdcb5
Revises: 67fb40cf09a6
Create Date: 2026-01-09 00:29:56.352498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a971acbdcb5'
down_revision: Union[str, None] = '67fb40cf09a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum type first
    payment_status_enum = sa.Enum('pending', 'authorized', 'succeeded', 'failed', 'refunded', name='payment_status_enum')
    payment_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('bookings', sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('driver_payout', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('stripe_charge_id', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('stripe_refund_id', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('payment_method_id', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', payment_status_enum, nullable=False, server_default='pending'))
    # Create bookingstatus enum type
    bookingstatus_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='bookingstatus')
    bookingstatus_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=bookingstatus_enum,
               existing_nullable=False,
               postgresql_using="upper(status)::bookingstatus")
    
    op.create_unique_constraint(None, 'bookings', ['stripe_payment_intent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='unique')
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='bookingstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('bookings', 'pickup_time')
    op.drop_column('bookings', 'payment_status')
    
    # Drop enum type
    payment_status_enum = sa.Enum('pending', 'authorized', 'succeeded', 'failed', 'refunded', name='payment_status_enum')
    payment_status_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_column('bookings', 'payment_method_id')
    op.drop_column('bookings', 'stripe_refund_id')
    op.drop_column('bookings', 'stripe_charge_id')
    op.drop_column('bookings', 'stripe_payment_intent_id')
    op.drop_column('bookings', 'driver_payout')
    op.drop_column('bookings', 'platform_fee')
    # ### end Alembic commands ###
