"""Add payment columns

Revision ID: 67fb40cf09a6
Revises: 72fc82b962ea
Create Date: 2026-01-08 23:28:57.672211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fb40cf09a6'
down_revision: Union[str, None] = '72fc82b962ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('driver_payout', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('stripe_charge_id', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('stripe_refund_id', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('payment_method_id', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.Enum('pending', 'authorized', 'succeeded', 'failed', 'refunded', name='payment_status_enum'), nullable=False))
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='bookingstatus'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'bookings', ['stripe_payment_intent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='unique')
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='bookingstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'payment_method_id')
    op.drop_column('bookings', 'stripe_refund_id')
    op.drop_column('bookings', 'stripe_charge_id')
    op.drop_column('bookings', 'stripe_payment_intent_id')
    op.drop_column('bookings', 'driver_payout')
    op.drop_column('bookings', 'platform_fee')
    # ### end Alembic commands ###
