"""add_ratings_table

Revision ID: ddd951f035af
Revises: 4a971acbdcb5
Create Date: 2026-01-09 22:28:50.743011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd951f035af'
down_revision: Union[str, None] = '4a971acbdcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'pickup_time')
    # ### end Alembic commands ###
