"""Add driver metadata fields

Revision ID: 37e0d35440b1
Revises: dc0928bee0d7
Create Date: 2026-01-09 02:08:50.574161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e0d35440b1'
down_revision: Union[str, Sequence[str], None] = 'dc0928bee0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Truncate table to handle ID type change (Dev environment only!)
    op.execute("TRUNCATE TABLE users CASCADE")
    
    # 2. Drop default value (sequence) which conflicts with UUID
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    
    op.add_column('users', sa.Column('car_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('car_color', sa.String(), nullable=True))
    op.add_column('users', sa.Column('license_plate', sa.String(), nullable=True))
    op.add_column('users', sa.Column('fcm_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('stripe_connect_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('stripe_charges_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('stripe_payouts_enabled', sa.Boolean(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               postgresql_using='gen_random_uuid()',
               existing_nullable=False)
    op.create_index(op.f('ix_users_stripe_connect_id'), 'users', ['stripe_connect_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_connect_id'), table_name='users')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'stripe_payouts_enabled')
    op.drop_column('users', 'stripe_charges_enabled')
    op.drop_column('users', 'stripe_connect_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'fcm_token')
    op.drop_column('users', 'license_plate')
    op.drop_column('users', 'car_color')
    op.drop_column('users', 'car_model')
    # ### end Alembic commands ###
