"""add_rating_stats_columns

Revision ID: 92bfd0fa56e9
Revises: e5d78b015d55
Create Date: 2026-01-09 22:27:23.493859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bfd0fa56e9'
down_revision: Union[str, Sequence[str], None] = 'e5d78b015d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('average_rating_as_driver', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('average_rating_as_passenger', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('total_ratings_as_driver', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('total_ratings_as_passenger', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('total_completed_rides_as_driver', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('total_completed_rides_as_passenger', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('is_top_rated_driver', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified_driver', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified_driver')
    op.drop_column('users', 'is_top_rated_driver')
    op.drop_column('users', 'total_completed_rides_as_passenger')
    op.drop_column('users', 'total_completed_rides_as_driver')
    op.drop_column('users', 'total_ratings_as_passenger')
    op.drop_column('users', 'total_ratings_as_driver')
    op.drop_column('users', 'average_rating_as_passenger')
    op.drop_column('users', 'average_rating_as_driver')
    # ### end Alembic commands ###
