"""Add profile and verification fields

Revision ID: ce7dc1dffccc
Revises: 92bfd0fa56e9
Create Date: 2026-01-10 07:17:35.639229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7dc1dffccc'
down_revision: Union[str, Sequence[str], None] = '92bfd0fa56e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('profile_photo_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('sjsu_email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('identity_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('sjsu_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('student_id', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('phone_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('account_deletion_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('account_deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_sjsu_email'), 'users', ['sjsu_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sjsu_email'), table_name='users')
    op.drop_column('users', 'account_deleted_at')
    op.drop_column('users', 'account_deletion_requested_at')
    op.drop_column('users', 'password_reset_expires_at')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'phone_verification_expires_at')
    op.drop_column('users', 'phone_verification_code')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'student_id')
    op.drop_column('users', 'sjsu_email')
    op.drop_column('users', 'identity_verified')
    op.drop_column('users', 'sjsu_email_verified')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'profile_photo_url')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
